// <auto-generated />
using System;
using GuideMe.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GuideMe.Migrations
{
    [DbContext(typeof(GuideMeContext))]
    partial class GuideMeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GuideMe.Models.ChatMessage", b =>
                {
                    b.Property<int>("ChatMessageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChatMessageId"));

                    b.Property<string>("Attachment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<string>("MessageText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SentAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("ChatMessageId")
                        .HasName("PK__ChatMess__9AB6103552931227");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("ChatMessages");
                });

            modelBuilder.Entity("GuideMe.Models.ContestEntry", b =>
                {
                    b.Property<int>("ContestEntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContestEntryId"));

                    b.Property<int>("ContestId")
                        .HasColumnType("int");

                    b.Property<string>("Descriptions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Submission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("VoteCount")
                        .HasColumnType("int");

                    b.HasKey("ContestEntryId")
                        .HasName("PK__ContestE__C402F8B8BF22DB27");

                    b.HasIndex("ContestId");

                    b.HasIndex("UserId");

                    b.ToTable("ContestEntry", (string)null);
                });

            modelBuilder.Entity("GuideMe.Models.Event", b =>
                {
                    b.Property<int>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventId"));

                    b.Property<string>("EventDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EventEndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("EventLocation")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("EventStartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("EventTime")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("EventTitle")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("IsAdded")
                        .HasColumnType("bit");

                    b.Property<bool?>("IsApproved")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<bool>("IsExpired")
                        .HasColumnType("bit");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("EventId")
                        .HasName("PK__Events__7944C810DE62B743");

                    b.HasIndex("UserId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("GuideMe.Models.Group", b =>
                {
                    b.Property<int>("GroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupId"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Location")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateOnly?>("TravelEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("TravelStartDate")
                        .HasColumnType("date");

                    b.HasKey("GroupId")
                        .HasName("PK__Groups__149AF36A67D6DE83");

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("GuideMe.Models.GroupMember", b =>
                {
                    b.Property<int>("GroupMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GroupMemberId"));

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime");

                    b.Property<string>("LeaveReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("GroupMemberId")
                        .HasName("PK__GroupMem__34481292F805F964");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("GuideMe.Models.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<DateOnly?>("LocationCreatedAt")
                        .HasColumnType("date");

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.HasKey("LocationId")
                        .HasName("PK__Location__E7FEA497411B474C");

                    b.ToTable("Locations");
                });

            modelBuilder.Entity("GuideMe.Models.Notification", b =>
                {
                    b.Property<int>("NotificationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NotificationId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<bool?>("IsRead")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("NotificationId")
                        .HasName("PK__Notifica__20CF2E122FC975B5");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("GuideMe.Models.PostLike", b =>
                {
                    b.Property<int>("LikeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LikeId"));

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LikeId")
                        .HasName("PK__PostLike__A2922C143D89E62B");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("PostLike", (string)null);
                });

            modelBuilder.Entity("GuideMe.Models.Province", b =>
                {
                    b.Property<int>("ProvinceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProvinceId"));

                    b.Property<string>("ProvinceDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceImage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProvinceName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ProvinceId")
                        .HasName("PK__Provienc__D72D03A0712A4C13");

                    b.ToTable("Province", (string)null);
                });

            modelBuilder.Entity("GuideMe.Models.UrbanTreasure", b =>
                {
                    b.Property<int>("UrbanTreasureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UrbanTreasureId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("ProvinceId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UrbanTreasureId")
                        .HasName("PK__UrbanTre__79281DDF042F0DFC");

                    b.HasIndex("ProvinceId");

                    b.HasIndex("UserId");

                    b.ToTable("UrbanTreasures");
                });

            modelBuilder.Entity("GuideMe.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("LastLogin")
                        .HasColumnType("datetime");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Role")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserImage")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId")
                        .HasName("PK__Users__1788CC4CD2E2DA80");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__A9D1053431CFB59C")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GuideMe.Models.UserComment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int>("PostId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("CommentId")
                        .HasName("PK__UserComm__C3B4DFCA370A8030");

                    b.HasIndex("PostId");

                    b.HasIndex("UserId");

                    b.ToTable("UserComment", (string)null);
                });

            modelBuilder.Entity("GuideMe.Models.UserPost", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PostId"));

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("MediaPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("PostId")
                        .HasName("PK__UserPost__AA12601833B44BC8");

                    b.HasIndex("UserId");

                    b.ToTable("UserPost", (string)null);
                });

            modelBuilder.Entity("GuideMe.Models.UserVote", b =>
                {
                    b.Property<int>("UserVoteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserVoteId"));

                    b.Property<int>("ContestEntryId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("VoteDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.HasKey("UserVoteId")
                        .HasName("PK__UserVote__0F0C36EC326F3BEC");

                    b.HasIndex("ContestEntryId");

                    b.HasIndex("UserId");

                    b.ToTable("UserVote", (string)null);
                });

            modelBuilder.Entity("GuideMe.Models.WeatherForecast", b =>
                {
                    b.Property<int>("WeatherId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WeatherId"));

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Temperature")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("WeatherId")
                        .HasName("PK__WeatherF__0BF97BF533F44185");

                    b.ToTable("WeatherForecasts");
                });

            modelBuilder.Entity("GuideMe.Models.WeeklyContest", b =>
                {
                    b.Property<int>("ContestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContestId"));

                    b.Property<string>("ContestPhase")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContestType")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Instructions")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime");

                    b.Property<string>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int?>("WinnerUserId")
                        .HasColumnType("int");

                    b.HasKey("ContestId")
                        .HasName("PK__WeeklyCo__87DE0B1A91583540");

                    b.HasIndex("UserId");

                    b.ToTable("WeeklyContest", (string)null);
                });

            modelBuilder.Entity("GuideMe.Models.ChatMessage", b =>
                {
                    b.HasOne("GuideMe.Models.Group", "Group")
                        .WithMany("ChatMessages")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK__ChatMessa__Group__3BFFE745");

                    b.HasOne("GuideMe.Models.User", "User")
                        .WithMany("ChatMessages")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__ChatMessa__UserI__3B0BC30C");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GuideMe.Models.ContestEntry", b =>
                {
                    b.HasOne("GuideMe.Models.WeeklyContest", "Contest")
                        .WithMany("ContestEntries")
                        .HasForeignKey("ContestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ContestEntry_WeeklyContest");

                    b.HasOne("GuideMe.Models.User", "User")
                        .WithMany("ContestEntries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ContestEntry_User");

                    b.Navigation("Contest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GuideMe.Models.Event", b =>
                {
                    b.HasOne("GuideMe.Models.User", "User")
                        .WithMany("Events")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Events__UserId__6FE99F9F");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GuideMe.Models.GroupMember", b =>
                {
                    b.HasOne("GuideMe.Models.Group", "Group")
                        .WithMany("GroupMembers")
                        .HasForeignKey("GroupId")
                        .IsRequired()
                        .HasConstraintName("FK__GroupMemb__Group__373B3228");

                    b.HasOne("GuideMe.Models.User", "User")
                        .WithMany("GroupMembers")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__GroupMemb__UserI__36470DEF");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GuideMe.Models.Notification", b =>
                {
                    b.HasOne("GuideMe.Models.User", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__Notificat__IsRea__3F115E1A");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GuideMe.Models.PostLike", b =>
                {
                    b.HasOne("GuideMe.Models.UserPost", "Post")
                        .WithMany("PostLikes")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_PostLike");

                    b.HasOne("GuideMe.Models.User", "User")
                        .WithMany("PostLikes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserLike");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GuideMe.Models.UrbanTreasure", b =>
                {
                    b.HasOne("GuideMe.Models.Province", "Province")
                        .WithMany("UrbanTreasures")
                        .HasForeignKey("ProvinceId")
                        .IsRequired()
                        .HasConstraintName("FK_UrbanTreasures_Province");

                    b.HasOne("GuideMe.Models.User", "User")
                        .WithMany("UrbanTreasures")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UrbanTreasures_Users");

                    b.Navigation("Province");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GuideMe.Models.UserComment", b =>
                {
                    b.HasOne("GuideMe.Models.UserPost", "Post")
                        .WithMany("UserComments")
                        .HasForeignKey("PostId")
                        .IsRequired()
                        .HasConstraintName("FK_Post");

                    b.HasOne("GuideMe.Models.User", "User")
                        .WithMany("UserComments")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_UserComment");

                    b.Navigation("Post");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GuideMe.Models.UserPost", b =>
                {
                    b.HasOne("GuideMe.Models.User", "User")
                        .WithMany("UserPosts")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK_User");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GuideMe.Models.UserVote", b =>
                {
                    b.HasOne("GuideMe.Models.ContestEntry", "ContestEntry")
                        .WithMany("UserVotes")
                        .HasForeignKey("ContestEntryId")
                        .IsRequired()
                        .HasConstraintName("FK__UserVote__Contes__4865BE2A");

                    b.HasOne("GuideMe.Models.User", "User")
                        .WithMany("UserVotes")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__UserVote__UserId__477199F1");

                    b.Navigation("ContestEntry");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GuideMe.Models.WeeklyContest", b =>
                {
                    b.HasOne("GuideMe.Models.User", "User")
                        .WithMany("WeeklyContests")
                        .HasForeignKey("UserId")
                        .IsRequired()
                        .HasConstraintName("FK__WeeklyCon__UserI__76619304");

                    b.Navigation("User");
                });

            modelBuilder.Entity("GuideMe.Models.ContestEntry", b =>
                {
                    b.Navigation("UserVotes");
                });

            modelBuilder.Entity("GuideMe.Models.Group", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("GroupMembers");
                });

            modelBuilder.Entity("GuideMe.Models.Province", b =>
                {
                    b.Navigation("UrbanTreasures");
                });

            modelBuilder.Entity("GuideMe.Models.User", b =>
                {
                    b.Navigation("ChatMessages");

                    b.Navigation("ContestEntries");

                    b.Navigation("Events");

                    b.Navigation("GroupMembers");

                    b.Navigation("Notifications");

                    b.Navigation("PostLikes");

                    b.Navigation("UrbanTreasures");

                    b.Navigation("UserComments");

                    b.Navigation("UserPosts");

                    b.Navigation("UserVotes");

                    b.Navigation("WeeklyContests");
                });

            modelBuilder.Entity("GuideMe.Models.UserPost", b =>
                {
                    b.Navigation("PostLikes");

                    b.Navigation("UserComments");
                });

            modelBuilder.Entity("GuideMe.Models.WeeklyContest", b =>
                {
                    b.Navigation("ContestEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
